### ISSUE TITLE
Isseu running - does not work on Mac

### ISSUE THREAD

**Issue by sada-narayanappa** [chickenbestlover/RNN-Time-series-Anomaly-Detection#12]
When I run I get the following error - could you help me how to fixe this
It uses default ecg and 

python3  1_train_predictor.py --device cpu --data ecg --filename chfdb_chf13_45590.pkl
=> Start training from scratch
-----------------------------------------------------------------------------------------
Namespace(augment=True, batch_size=64, bptt=50, clip=10, data='ecg', device='cpu', dropout=0.2, emsize=32, epochs=400, eval_batch_size=64, filename='chfdb_chf13_45590.pkl', log_interval=10, lr=0.0002, model='LSTM', nhid=32, nlayers=2, prediction_window_size=10, pretrained=False, res_connection=False, resume=False, save_fig=False, save_interval=10, seed=1111, teacher_forcing_ratio=0.7, tied=False, weight_decay=0.0001)
-----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "1_train_predictor.py", line 320, in <module>
    train(args,model,train_dataset,epoch)
  File "1_train_predictor.py", line 228, in train
    loss1 = criterion(outSeq1.view(args.batch_size,-1), targetSeq.view(args.batch_size,-1))
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/TH/generic/THTensor.cpp:237

**Comment by chickenbestlover** [comment]
See #2.

**Comment by sada-narayanappa** [comment]
Yeah that works. 

There is one more after that, we need "contiguous()" call - having done that it works. 
It would be great to update the code with those changes.
