### ISSUE TITLE
problem with tensor's view?

### ISSUE THREAD

**Issue by mckeown12** [chickenbestlover/RNN-Time-series-Anomaly-Detection#2]
I am attempting to run the following: 

`<python 1_train_predictor.py --data nyc_taxi --filename nyc_taxi.pkl`
Here is the traceback:

`Traceback (most recent call last):
  File "1_train_predictor.py", line 322, in <module>
    train(args,model,train_dataset,epoch)
  File "1_train_predictor.py", line 230, in train
    loss1 = criterion(outSeq1.view(args.batch_size,-1), targetSeq.view(args.batch_size,-1))
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/TH/generic/THTensor.cpp:280`

 Any ideas?

**Comment by chickenbestlover** [comment]
Since I do not get an error on my computer, I have no idea why the error occurred. 
But contiguous error is easy to fix. try this:
`loss1 = criterion(outSeq1.contiguous().view(args.batch_size,-1), targetSeq.contiguous().view(args.batch_size,-1))`

**Comment by mckeown12** [comment]
Me as well. Thanks.

**Comment by qhwscream** [comment]
hello,when I tried to run the code,some errors happened like these:
1. FileNotFoundError: [Errno 2] No such file or directory: 'dataset/ecg/labeled/train/chfdb_chf14_45590.pkl'
2.I changed another dataset,the error is:RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimeten/src/TH/generic/THTensor.cpp:237
 
thank you!

**Comment by qhwscream** [comment]
Me as well. Thanks.

**Comment by qhwscream** [comment]
hello ,I want to ask a question:Why I don't have  the 'nyc_taxi --filename nyc_taxi.pkl'dataset,when I running 0_download_dataset.py ,it also has 5 dataset, the urls dict() doesn't includes the  'nyc_taxi --filename nyc_taxi.pkl'.Thank you!
