### ISSUE TITLE
How to improve the recall

### ISSUE THREAD

**Issue by chi2liu** [chickenbestlover/RNN-Time-series-Anomaly-Detection#3]
The predicting results are generally good.
But we can see that the prediction can not fit good on the lowest value.
Can we imporve it?
how many ways that we can do to improve the recall?
can u Give me a little hint? or we can discuss about it?
thanks a lot.

**Comment by chickenbestlover** [comment]
Nowadays reconstruction models are more popular than prediction models in deep learning based time-series anomaly detection. See #9
